#!/bin/bash

#==============================================================================
#title           : checkversion
#description     : Check new update or defintinion of Runecast Analyzer
#author	      	 : Julien Mousqueton (@JMousqueton)
#date            : 20200605
#version         : 0.4
#usage		       : bash checkversion
#notes           : Send an email if a new version is available.
#==============================================================================
# Variables
#==============================================================================
From="runecast@mousqueton.io"
To="julien@mousqueton.io"
Root="/var/www/updates-runecast"
#==============================================================================
# Main program
#==============================================================================
# Check for mail
mail_path=$( which mail )
if [ ! -f $mail_path ]; then
    echo "mail not available"
    exit 1
fi

# Check for new version of Runecast Analyzer
if ! [[ -z $(find $Root/runecast-analyzer-vmware/version.txt -mmin -180) ]]; then
    # The file was changed, so:
    # echo "New Version : Change detected"
    mail -r $From -s "New Runecast version" $To  < $Root/runecast-analyzer-vmware/version.txt
else
    echo "New Version : No change"
fi

# Check for new Definition Update for Runecast Analyzer
if ! [[ -z $(find $Root/definitions/version.txt -cmin -180) ]]; then
    # The file was changed, so:
    echo "New Definition : Chnage detected"
    mail -r $From -s "New Runecast definition" $To < $Root/definitions/version.txt
else
    echo "New Definition : No change"
fi
