#!/bin/bash

#==============================================================================
#title           : RunecastUpdateDefinition
#description     : Update Runecast Definition repository if new version
#author	      	 : Julien Mousqueton (@JMousqueton)
#date            : 20200605
#version         : 1.0
#usage		       : RunecastUpdateDefinition
#notes           : Checked on Ubuntu.
#==============================================================================
# Variables
#==============================================================================
Root="/var/www/updates-runecast" # Change with your own path
Mail=true
To='julien@mousqueton.me'
From="runecast@mousqueton.io"

#==============================================================================
# Constant
#==============================================================================
TEMP=$(mktemp -u XXXXXXXXX)
#==============================================================================
# Main
#==============================================================================
curl https://updates.runecast.com/definitions/version.txt -o /tmp/$TEMP

if ! cmp -s "$Root/definitions/version.txt" "/tmp/$TEMP"; then
  curl https://updates.runecast.com/definitions/kbupdates.bin -o $Root/definitions/kbupdates.bin
  curl https://updates.runecast.com/definitions/version.txt -o $Root/definitions/version.txt
  if [ $Mail ]; then
    mail -r $From -s "New Runecast definition" $To < $Root/definitions/version.txt
  fi
fi
rm /tmp/$TEMP
